//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 10:00:45 AM EST 
//


package org.rac.structure.patronImportSchema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rac.structure.patronImportSchema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rac.structure.patronImportSchema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatronAddresses }
     * 
     */
    public PatronAddresses createPatronAddresses() {
        return new PatronAddresses();
    }

    /**
     * Create an instance of {@link PatronForms }
     * 
     */
    public PatronForms createPatronForms() {
        return new PatronForms();
    }

    /**
     * Create an instance of {@link PatronVisitsSubjects }
     * 
     */
    public PatronVisitsSubjects createPatronVisitsSubjects() {
        return new PatronVisitsSubjects();
    }

    /**
     * Create an instance of {@link NameComplexType }
     * 
     */
    public NameComplexType createNameComplexType() {
        return new NameComplexType();
    }

    /**
     * Create an instance of {@link PatronVisitsNames }
     * 
     */
    public PatronVisitsNames createPatronVisitsNames() {
        return new PatronVisitsNames();
    }

    /**
     * Create an instance of {@link PatronPublicationsNames }
     * 
     */
    public PatronPublicationsNames createPatronPublicationsNames() {
        return new PatronPublicationsNames();
    }

    /**
     * Create an instance of {@link PatronPhoneNumbers }
     * 
     */
    public PatronPhoneNumbers createPatronPhoneNumbers() {
        return new PatronPhoneNumbers();
    }

    /**
     * Create an instance of {@link PatronPublications }
     * 
     */
    public PatronPublications createPatronPublications() {
        return new PatronPublications();
    }

    /**
     * Create an instance of {@link PatronPublicationsSubjects }
     * 
     */
    public PatronPublicationsSubjects createPatronPublicationsSubjects() {
        return new PatronPublicationsSubjects();
    }

    /**
     * Create an instance of {@link Patron }
     * 
     */
    public Patron createPatron() {
        return new Patron();
    }

    /**
     * Create an instance of {@link PatronVisitsResources }
     * 
     */
    public PatronVisitsResources createPatronVisitsResources() {
        return new PatronVisitsResources();
    }

    /**
     * Create an instance of {@link PatronRecords }
     * 
     */
    public PatronRecords createPatronRecords() {
        return new PatronRecords();
    }

    /**
     * Create an instance of {@link PatronFunding }
     * 
     */
    public PatronFunding createPatronFunding() {
        return new PatronFunding();
    }

    /**
     * Create an instance of {@link PatronVisits }
     * 
     */
    public PatronVisits createPatronVisits() {
        return new PatronVisits();
    }

}
