//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.09 at 11:02:27 AM EDT 
//


package org.rac.structure.patronImportSchema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for patronVisits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patronVisits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactArchivist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="visitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detailsOnResourcesUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedBoolean1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="userDefinedString1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="researchPurpose" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronVisitsSubjects" type="{}patronVisitsSubjects" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronVisitsNames" type="{}patronVisitsNames" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patronVisits", propOrder = {
    "contactArchivist",
    "topic",
    "visitDate",
    "visitType",
    "detailsOnResourcesUsed",
    "userDefinedBoolean1",
    "userDefinedString1",
    "userDefinedText1",
    "researchPurpose",
    "patronVisitsSubjects",
    "patronVisitsNames"
})
public class PatronVisits {

    protected String contactArchivist;
    protected String topic;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    protected String visitType;
    protected String detailsOnResourcesUsed;
    protected Boolean userDefinedBoolean1;
    protected String userDefinedString1;
    protected String userDefinedText1;
    protected List<String> researchPurpose;
    protected List<PatronVisitsSubjects> patronVisitsSubjects;
    protected List<PatronVisitsNames> patronVisitsNames;

    /**
     * Gets the value of the contactArchivist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactArchivist() {
        return contactArchivist;
    }

    /**
     * Sets the value of the contactArchivist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactArchivist(String value) {
        this.contactArchivist = value;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the visitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the visitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitType() {
        return visitType;
    }

    /**
     * Sets the value of the visitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitType(String value) {
        this.visitType = value;
    }

    /**
     * Gets the value of the detailsOnResourcesUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailsOnResourcesUsed() {
        return detailsOnResourcesUsed;
    }

    /**
     * Sets the value of the detailsOnResourcesUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailsOnResourcesUsed(String value) {
        this.detailsOnResourcesUsed = value;
    }

    /**
     * Gets the value of the userDefinedBoolean1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedBoolean1() {
        return userDefinedBoolean1;
    }

    /**
     * Sets the value of the userDefinedBoolean1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedBoolean1(Boolean value) {
        this.userDefinedBoolean1 = value;
    }

    /**
     * Gets the value of the userDefinedString1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString1() {
        return userDefinedString1;
    }

    /**
     * Sets the value of the userDefinedString1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString1(String value) {
        this.userDefinedString1 = value;
    }

    /**
     * Gets the value of the userDefinedText1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText1() {
        return userDefinedText1;
    }

    /**
     * Sets the value of the userDefinedText1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText1(String value) {
        this.userDefinedText1 = value;
    }

    /**
     * Gets the value of the researchPurpose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the researchPurpose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResearchPurpose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResearchPurpose() {
        if (researchPurpose == null) {
            researchPurpose = new ArrayList<String>();
        }
        return this.researchPurpose;
    }

    /**
     * Gets the value of the patronVisitsSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronVisitsSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronVisitsSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronVisitsSubjects }
     * 
     * 
     */
    public List<PatronVisitsSubjects> getPatronVisitsSubjects() {
        if (patronVisitsSubjects == null) {
            patronVisitsSubjects = new ArrayList<PatronVisitsSubjects>();
        }
        return this.patronVisitsSubjects;
    }

    /**
     * Gets the value of the patronVisitsNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronVisitsNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronVisitsNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronVisitsNames }
     * 
     * 
     */
    public List<PatronVisitsNames> getPatronVisitsNames() {
        if (patronVisitsNames == null) {
            patronVisitsNames = new ArrayList<PatronVisitsNames>();
        }
        return this.patronVisitsNames;
    }

}
