//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 11:27:42 AM EDT 
//


package org.rac.structure.patronImportSchema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for patronVisits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patronVisits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactArchivist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="researchPurpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="patronVisitsSubjects" type="{}patronVisitsSubjects" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patronVisits", propOrder = {
    "contactArchivist",
    "researchPurpose",
    "topic",
    "visitDate",
    "patronVisitsSubjects"
})
public class PatronVisits {

    protected String contactArchivist;
    protected String researchPurpose;
    protected String topic;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    protected List<PatronVisitsSubjects> patronVisitsSubjects;

    /**
     * Gets the value of the contactArchivist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactArchivist() {
        return contactArchivist;
    }

    /**
     * Sets the value of the contactArchivist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactArchivist(String value) {
        this.contactArchivist = value;
    }

    /**
     * Gets the value of the researchPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResearchPurpose() {
        return researchPurpose;
    }

    /**
     * Sets the value of the researchPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResearchPurpose(String value) {
        this.researchPurpose = value;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the visitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the patronVisitsSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronVisitsSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronVisitsSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronVisitsSubjects }
     * 
     * 
     */
    public List<PatronVisitsSubjects> getPatronVisitsSubjects() {
        if (patronVisitsSubjects == null) {
            patronVisitsSubjects = new ArrayList<PatronVisitsSubjects>();
        }
        return this.patronVisitsSubjects;
    }

}
