//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 10:00:45 AM EST 
//


package org.rac.structure.patronImportSchema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patronPublicationsNames complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patronPublicationsNames">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameLinkRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameLinkForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{}nameComplexType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patronPublicationsNames", propOrder = {
    "nameLinkRole",
    "nameLinkForm",
    "name"
})
public class PatronPublicationsNames {

    protected String nameLinkRole;
    protected String nameLinkForm;
    @XmlElement(required = true)
    protected NameComplexType name;

    /**
     * Gets the value of the nameLinkRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLinkRole() {
        return nameLinkRole;
    }

    /**
     * Sets the value of the nameLinkRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLinkRole(String value) {
        this.nameLinkRole = value;
    }

    /**
     * Gets the value of the nameLinkForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLinkForm() {
        return nameLinkForm;
    }

    /**
     * Sets the value of the nameLinkForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLinkForm(String value) {
        this.nameLinkForm = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameComplexType }
     *     
     */
    public NameComplexType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameComplexType }
     *     
     */
    public void setName(NameComplexType value) {
        this.name = value;
    }

}
