//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 11:27:42 AM EDT 
//


package org.rac.structure.patronImportSchema;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for patron complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patron">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patronType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="howDidYouHearAboutUs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primaryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="restOfName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="institutionalAffiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patronNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedDate1" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="userDefinedDate2" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="userDefinedBoolean1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="userDefinedBoolean2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="userDefinedInteger1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="userDefinedInteger2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="userDefinedReal1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="userDefinedReal2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="userDefinedString1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedString2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedString3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patronAddresses" type="{}patronAddresses" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronPhoneNumbers" type="{}patronPhoneNumbers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronVisits" type="{}patronVisits" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronFunding" type="{}patronFunding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patronPublications" type="{}patronPublications" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patron", propOrder = {
    "patronType",
    "howDidYouHearAboutUs",
    "primaryName",
    "restOfName",
    "prefix",
    "suffix",
    "title",
    "institutionalAffiliation",
    "department",
    "patronNotes",
    "email1",
    "email2",
    "userDefinedDate1",
    "userDefinedDate2",
    "userDefinedBoolean1",
    "userDefinedBoolean2",
    "userDefinedInteger1",
    "userDefinedInteger2",
    "userDefinedReal1",
    "userDefinedReal2",
    "userDefinedString1",
    "userDefinedString2",
    "userDefinedString3",
    "userDefinedText1",
    "userDefinedText2",
    "userDefinedText3",
    "userDefinedText4",
    "patronAddresses",
    "patronPhoneNumbers",
    "patronVisits",
    "patronFunding",
    "patronPublications"
})
public class Patron {

    @XmlElement(required = true)
    protected String patronType;
    protected String howDidYouHearAboutUs;
    @XmlElement(required = true)
    protected String primaryName;
    @XmlElement(required = true)
    protected String restOfName;
    protected String prefix;
    protected String suffix;
    protected String title;
    protected String institutionalAffiliation;
    protected String department;
    protected String patronNotes;
    protected String email1;
    protected String email2;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar userDefinedDate1;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar userDefinedDate2;
    protected Boolean userDefinedBoolean1;
    protected Boolean userDefinedBoolean2;
    protected BigInteger userDefinedInteger1;
    protected BigInteger userDefinedInteger2;
    protected BigDecimal userDefinedReal1;
    protected BigDecimal userDefinedReal2;
    protected String userDefinedString1;
    protected String userDefinedString2;
    protected String userDefinedString3;
    protected String userDefinedText1;
    protected String userDefinedText2;
    protected String userDefinedText3;
    protected String userDefinedText4;
    protected List<PatronAddresses> patronAddresses;
    protected List<PatronPhoneNumbers> patronPhoneNumbers;
    protected List<PatronVisits> patronVisits;
    protected List<PatronFunding> patronFunding;
    protected List<PatronPublications> patronPublications;

    /**
     * Gets the value of the patronType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatronType() {
        return patronType;
    }

    /**
     * Sets the value of the patronType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatronType(String value) {
        this.patronType = value;
    }

    /**
     * Gets the value of the howDidYouHearAboutUs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHowDidYouHearAboutUs() {
        return howDidYouHearAboutUs;
    }

    /**
     * Sets the value of the howDidYouHearAboutUs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHowDidYouHearAboutUs(String value) {
        this.howDidYouHearAboutUs = value;
    }

    /**
     * Gets the value of the primaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryName() {
        return primaryName;
    }

    /**
     * Sets the value of the primaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryName(String value) {
        this.primaryName = value;
    }

    /**
     * Gets the value of the restOfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestOfName() {
        return restOfName;
    }

    /**
     * Sets the value of the restOfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestOfName(String value) {
        this.restOfName = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the institutionalAffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionalAffiliation() {
        return institutionalAffiliation;
    }

    /**
     * Sets the value of the institutionalAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionalAffiliation(String value) {
        this.institutionalAffiliation = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the patronNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatronNotes() {
        return patronNotes;
    }

    /**
     * Sets the value of the patronNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatronNotes(String value) {
        this.patronNotes = value;
    }

    /**
     * Gets the value of the email1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * Sets the value of the email1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail1(String value) {
        this.email1 = value;
    }

    /**
     * Gets the value of the email2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * Sets the value of the email2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail2(String value) {
        this.email2 = value;
    }

    /**
     * Gets the value of the userDefinedDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserDefinedDate1() {
        return userDefinedDate1;
    }

    /**
     * Sets the value of the userDefinedDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserDefinedDate1(XMLGregorianCalendar value) {
        this.userDefinedDate1 = value;
    }

    /**
     * Gets the value of the userDefinedDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserDefinedDate2() {
        return userDefinedDate2;
    }

    /**
     * Sets the value of the userDefinedDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserDefinedDate2(XMLGregorianCalendar value) {
        this.userDefinedDate2 = value;
    }

    /**
     * Gets the value of the userDefinedBoolean1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedBoolean1() {
        return userDefinedBoolean1;
    }

    /**
     * Sets the value of the userDefinedBoolean1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedBoolean1(Boolean value) {
        this.userDefinedBoolean1 = value;
    }

    /**
     * Gets the value of the userDefinedBoolean2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedBoolean2() {
        return userDefinedBoolean2;
    }

    /**
     * Sets the value of the userDefinedBoolean2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedBoolean2(Boolean value) {
        this.userDefinedBoolean2 = value;
    }

    /**
     * Gets the value of the userDefinedInteger1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserDefinedInteger1() {
        return userDefinedInteger1;
    }

    /**
     * Sets the value of the userDefinedInteger1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserDefinedInteger1(BigInteger value) {
        this.userDefinedInteger1 = value;
    }

    /**
     * Gets the value of the userDefinedInteger2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserDefinedInteger2() {
        return userDefinedInteger2;
    }

    /**
     * Sets the value of the userDefinedInteger2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserDefinedInteger2(BigInteger value) {
        this.userDefinedInteger2 = value;
    }

    /**
     * Gets the value of the userDefinedReal1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserDefinedReal1() {
        return userDefinedReal1;
    }

    /**
     * Sets the value of the userDefinedReal1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserDefinedReal1(BigDecimal value) {
        this.userDefinedReal1 = value;
    }

    /**
     * Gets the value of the userDefinedReal2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserDefinedReal2() {
        return userDefinedReal2;
    }

    /**
     * Sets the value of the userDefinedReal2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserDefinedReal2(BigDecimal value) {
        this.userDefinedReal2 = value;
    }

    /**
     * Gets the value of the userDefinedString1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString1() {
        return userDefinedString1;
    }

    /**
     * Sets the value of the userDefinedString1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString1(String value) {
        this.userDefinedString1 = value;
    }

    /**
     * Gets the value of the userDefinedString2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString2() {
        return userDefinedString2;
    }

    /**
     * Sets the value of the userDefinedString2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString2(String value) {
        this.userDefinedString2 = value;
    }

    /**
     * Gets the value of the userDefinedString3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString3() {
        return userDefinedString3;
    }

    /**
     * Sets the value of the userDefinedString3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString3(String value) {
        this.userDefinedString3 = value;
    }

    /**
     * Gets the value of the userDefinedText1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText1() {
        return userDefinedText1;
    }

    /**
     * Sets the value of the userDefinedText1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText1(String value) {
        this.userDefinedText1 = value;
    }

    /**
     * Gets the value of the userDefinedText2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText2() {
        return userDefinedText2;
    }

    /**
     * Sets the value of the userDefinedText2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText2(String value) {
        this.userDefinedText2 = value;
    }

    /**
     * Gets the value of the userDefinedText3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText3() {
        return userDefinedText3;
    }

    /**
     * Sets the value of the userDefinedText3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText3(String value) {
        this.userDefinedText3 = value;
    }

    /**
     * Gets the value of the userDefinedText4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText4() {
        return userDefinedText4;
    }

    /**
     * Sets the value of the userDefinedText4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText4(String value) {
        this.userDefinedText4 = value;
    }

    /**
     * Gets the value of the patronAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronAddresses }
     * 
     * 
     */
    public List<PatronAddresses> getPatronAddresses() {
        if (patronAddresses == null) {
            patronAddresses = new ArrayList<PatronAddresses>();
        }
        return this.patronAddresses;
    }

    /**
     * Gets the value of the patronPhoneNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronPhoneNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronPhoneNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronPhoneNumbers }
     * 
     * 
     */
    public List<PatronPhoneNumbers> getPatronPhoneNumbers() {
        if (patronPhoneNumbers == null) {
            patronPhoneNumbers = new ArrayList<PatronPhoneNumbers>();
        }
        return this.patronPhoneNumbers;
    }

    /**
     * Gets the value of the patronVisits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronVisits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronVisits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronVisits }
     * 
     * 
     */
    public List<PatronVisits> getPatronVisits() {
        if (patronVisits == null) {
            patronVisits = new ArrayList<PatronVisits>();
        }
        return this.patronVisits;
    }

    /**
     * Gets the value of the patronFunding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronFunding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronFunding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronFunding }
     * 
     * 
     */
    public List<PatronFunding> getPatronFunding() {
        if (patronFunding == null) {
            patronFunding = new ArrayList<PatronFunding>();
        }
        return this.patronFunding;
    }

    /**
     * Gets the value of the patronPublications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patronPublications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatronPublications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatronPublications }
     * 
     * 
     */
    public List<PatronPublications> getPatronPublications() {
        if (patronPublications == null) {
            patronPublications = new ArrayList<PatronPublications>();
        }
        return this.patronPublications;
    }

}
